### PR TITLE
Allow menus to be null and fix up menu_name lookup where term was not…

### PR DESCRIPTION
**Pull request by sherakama**
… being returned

How to test:
1. Install the current 7.x-3.x branch on a JSA website
2. Enable and create a subsite
3. Create a second subsite and it should PDO error out
4. Check out this branch
5. run drush updb -y
6. Try to create a third subsite and it should be successful.

@josephgknox FYI

### CODE REVIEW

**Comment by josephgknox** [comment]
Nice! Once this is merged, I'll test.

To be clear: once this PR is merged, the **latest** 7.x-3.x branch should work straight away, correct?

**Comment by sherakama** [comment]
@josephgknox,

After this is merged you will have to:
1. Re-deploy with the latest 7.x-3.x branch
2. Run `drush updb` or `update.php`
3. Create new subsite

**Comment by josephgknox** [comment]
Got it - thanks for keeping me in the loop.

**Comment by sherakama** [comment]
Thanks GG.

**Pull request merged**
