### PR TITLE
modiified condition to trigger on init rather than _context_page_cond…

### PR DESCRIPTION
**Pull request by boznik**
…ition

### CODE REVIEW

**Comment by sherakama** [comment]
Was the issue that the context condition was not being fired early enough?

hook_context_page_condition() is called from hook_page_build()
https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_page_build/7

This seems like an appropriate place for the context condition to be fired. What gets dropped?

**Comment by boznik** [comment]
yeah, it wasn't getting fired early enough. i tried some other hooks such as node_view but it still didn't add the block to the navigation. there may be something better than hook_init, but i didn't find it.

**Comment by sherakama** [comment]
re: https://github.com/SU-SWS/open_framework/pull/316

**Comment by sherakama** [comment]
https://github.com/SU-SWS/open_framework/blob/7.x-2.x/template.php#L522
[17:51] 
It calls the context blocks reaction and gets cached
[17:51] 
This is particular to the book type because it has a preprocess hook for its menu items
[17:51] 
If you change the theme to bartik or something else it works
[17:52] 
Which explains the ooo error and the need to put it at hook_init
[17:53] 
shea This static cache gets set: http://cgit.drupalcode.org/context/tree/plugins/context_reaction_block.inc#n367

**Pull request closed without merging**
