### PR TITLE
added revision id for loading subsite node

### PR DESCRIPTION
**Pull request by boznik**

### CODE REVIEW

**Comment by sherakama** [comment]
I checked on a fresh JSA install. There is always a vid present on a node even if it does not have revisions enabled on the content type. With other content types having revisions enabled the $nid == $vid portion of this pull request is invalid. I created a new node which had node/75 and vid/685. I think you can get rid of the null check and expect a vid. Throw an error if you don't get one.

**Comment by boznik** [comment]
There are multiple other functions using triggers to the function stanford_subsite_subsite_load_node_efq that are sending nid only.

**Comment by sherakama** [comment]
Im not sure. I don't think I've personally added anything outside of the project. Perhaps ask the gentleman who wrote it: https://github.com/SU-SWS/stanford_subsites/blame/25dff96f82258a8186a31a18a44b1095f180170a/stanford_subsites.inc#L701 ;)

**Comment by sherakama** [comment]
I like it. Works great.

**Comment by boznik** [comment]
woot

**Pull request merged**
