### PR TITLE
    Updated the pathauto alias update on subsite form submit so it do…

### PR DESCRIPTION
**Pull request by sherakama**
…esn't do EVERY node

### CODE REVIEW

**Comment by jbickar** [comment]
I'll test. I neglected to test `7.x-1.x-dev` before merging; I'll test that too.

**Comment by jbickar** [comment]
`Notice: Trying to get property of non-object in _get_subsite_paths() (line 234 of sites/all/modules/stanford/stanford_subsites/stanford_subsites.inc)`

That appears to be a different issue; do we have that tracked somewhere?

**Comment by sherakama** [comment]
@jbickar No we do not have that php notice error tracked. I have added a fix for it here.

**Comment by sherakama** [comment]
@jbickar nudge on this one before it gets too stale.

**Comment by jbickar** [comment]
I prefer "finely aged" to "stale"

**Comment by jbickar** [comment]
https://stanfordits.atlassian.net/browse/VPUE-582

**Pull request merged**
