### PR TITLE
7.x-2.0

### PR DESCRIPTION
**Pull request by sherakama**
Subsite 2.0 release

### CODE REVIEW

**Comment by sherakama** [comment]
@cjwest: Please to review.

**Comment by cjwest** [comment]
@sherakama,
What am I looking for in testing this?

**Comment by sherakama** [comment]
@cjwest,

For this one it is mostly code standards and grammar. This is the PR before I release version 2.0 of this module.

**Comment by cjwest** [comment]
Looks good to me, Mr. @sherakama!

**Comment by sherakama** [comment]
Thanks!

**Pull request merged**
